### PR TITLE
Feature/new cards

### PR DESCRIPTION
**Pull request by sofusalbertsen**

### CODE REVIEW

**Comment by sofusalbertsen** [comment]
@Kargamborgh Can I get you to verify that the id's of cards can be anything, or should I take the ID's from somewhere?

**Review by vuuan — CHANGES_REQUESTED** [review]
Please lint the file and check that there are same amount of starting and closing curly brackets

**Comment by sofusalbertsen** [comment]
Could see that I made a bad commit, messing things up.
Will see what GHA says now.

**Comment by sofusalbertsen** [comment]
@vuuan I would like this to be deployed to dev first to see if the card ID's given are something that is okay to have or not. Can you help out?

**Review by vuuan — APPROVED** [review]

**Review by vuuan — APPROVED** [review]

**Review by vuuan — APPROVED** [review]

**Review by vuuan — CHANGES_REQUESTED** [review]
.

**Review by vuuan — APPROVED** [review]

**Pull request merged**
